# dein
[[plugins]]
repo = 'Shougo/dein.vim'

# カッコ補完
[[plugins]]
repo = 'cohama/lexima.vim'

# カッコハイライト(公式より速いし見やすい)
[[plugins]]
repo = 'itchyny/vim-parenmatch'

# コメントアウト
[[plugins]]
repo = 'preservim/nerdcommenter'

# Mediawiki
[[plugins]]
repo = 'chikamichi/mediawiki.vim'

# Toml
[[plugins]]
repo  = 'cespare/vim-toml'

# 補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'

# deoplete plugin for clang
[[plugins]]
repo = 'zchee/deoplete-clang'
