[[plugins]]
repo = 'Shougo/dein.vim'

#lightline
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {'colorscheme': 'wombat'}
'''

# Toml
[[plugins]]
repo  = 'cespare/vim-toml'

# Golang
[[plugins]]
repo = 'fatih/vim-go'

# clang-format
[[plugins]]
repo = 'rhysd/vim-clang-format'

# neocomplcache
[[plugins]]
repo = 'Shougo/neocomplcache'

# deoplete
[[plugins]]
repo = "Shougo/deoplete.nvim"
on_i = 1
on_event = "InsertCharPre"
hook_source = """
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
  set completeopt-=preview
  " autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif
"""

[[plugins]]
repo = "aliva/vim-fish"

[[plugins]]
repo = "chikamichi/mediawiki.vim"

[[plugins]]
repo = "posva/vim-vue"

[[plugins]]
repo = "othree/yajs.vim"
