# python indent
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

# 補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'

# deoplete plugin for clang
[[plugins]]
repo = 'zchee/deoplete-clang'
